osbuild/fedora-bot

fedora_bot.py

Only use the package URl as fallback, also bump the Fedora rawhide version (currently hardcoded) to 37.

Use the Koji URL from the actual build

---

fedora_bot.py

The most recent notification by fedora-bot (which was actually for koji-osbuild) made me realize that the component is not included in the notification, which makes it harder to understand what just happened.

Include component in Slack notification

---

.github/workflows/poll-releases.yml
fedora_bot.py

As packit is removing the create_pr option we need to take care of
merging the pull requests in Fedora's dist-git ourselves.
The api key expires in 2 years from now (2024-04-28).
The code was tested with this test repo/PR: https://pagure.io/merge_test/pull-request/1

fedora-bot: Add support for merging PRs

---

fedora_bot.py

Currently the release version for koji-osbuild is set to 0 in its
specfile. The real fix is to change this upstream.
This workaround shall be reverted once
https://github.com/osbuild/koji-osbuild/pull/98 gets released as part of
koji-osbuild 7.

fedora-bot: Add workaround for koji-osbuild release

---

.github/workflows/poll-releases.yml
README.md

Currently the fedora-bot runs almost a little too frequently, so drop that to every 30mins (consistent with centos-bot).
Also, we need to update the README as it doesn't reflect the capabilities of the bot anymore.

Update readme and schedule

---

fedora_bot.py

In order to make the PRs that packit opens automatically useful we can check if all tests passed vs. just auto-merging the PR.
The tests are shown in Pagure's API as 'flags' (https://pagure.io/api/0/#pull_requests-tab) and we're querying their status, which can either be `success` or `failure`. Unfortunately there is no indication of whether tests are currently/still running, so we need to hardcode the amount of tests we expect so we don't prematurely merge a PR.

Check pr flags

---

.github/workflows/poll-releases.yml
fedora_bot.py

Pull out the hardcoded project list into command line argument.
---
This is a big step towards making this project more universal. Tested in "dry mode":
```
❱❱❱ podman run -it --rm -v .:/bot:ro localhost/fedora-bot /bot/fedora_bot.py --component osbuild:3 --component osbuild-composer:2 --component koji-osbuild:2
--- osbuild ---
Info: Checking for open pull requests of osbuild...
OK: There are currently no open pull requests for osbuild.
Info: Checking for missing updates of 'osbuild'...
Cloning into 'https://src.fedoraproject.org/rpms/osbuild.git'...
Checked out dist-git with branch 'rawhide'
Version osbuild 56 found in dist-git
Fedora 35: ✅ Build for osbuild 56 is available in Koji
Fedora 35: ✅ Update for osbuild 56 is available in Bodhi
Fedora 34: ✅ Build for osbuild 56 is available in …
```

fedora-bot: Parameterize components

---

.github/workflows/build-bot-container.yml
.github/workflows/poll-releases.yml
.github/workflows/reminder-bot.yml

The container is built and run on GitHub, so it makes more sense to also
host it on GitHub. This also gets rid of a project secret (as the
default GitHub token is sufficient for this), and makes it easier to
test changes on forks.
----
I tested this on my fork: Without any further modification, I [ran the workflow](https://github.com/martinpitt/fedora-bot/runs/6482525489?check_suite_focus=true), and it [built a container image](https://github.com/martinpitt/fedora-bot/pkgs/container/fedora-bot):
```
❱❱❱ podman run -it --rm  ghcr.io/martinpitt/fedora-bot:latest
Trying to pull ghcr.io/martinpitt/fedora-bot:latest...
Getting image source signatures
Copying blob 98d28a431257 done  
Copying blob 736fb53cfb11 done  
Copying blob de72a73b45a4 done  
Copying config d4d17383d2 done  
Writing …
```

Move container to GitHub container registry

---

fedora_bot.py
reminder_bot.py

Skip slack notifications if `$SLACK_WEBHOOK_URL` is not set.
---
In Cockpit and in my own upstream projects we don't use slack, but at some point I'd like to use fedora-bot to auto-land packit PRs.

fedora_bot: Make slack notifications optional

---

.github/workflows/build-bot-container.yml

Running third-party actions should be done with caution, as they have a
lot of access to your project and can be changed/captured at any time.
There is no reason right now to mistrust these actions, but at the same
time they don't really buy us anything: Running the commands directly is
shorter, easier to understand, and easier to debug locally.
---
Tested on my fork: [workflow run](https://github.com/martinpitt/fedora-bot/runs/6505322868?check_suite_focus=true), [container image](https://github.com/martinpitt/fedora-bot/pkgs/container/fedora-bot):
```
$ podman run -it --rm -v .:/bot:ro ghcr.io/martinpitt/fedora-bot /bot/fedora_bot.py -c umockdev:2
[...]
Info: Checking for missing updates of 'umockdev'...
Cloning into 'https://src.fedoraproject.org/rpms/umockdev.git'...
Checked out …
```

workflows: Use plain commands for building and pushing the container

---

fedora_bot.py

Commit 548103a2b55 introduced a bug: `num_tests` was a string, so the
comparison tried to compare a number to a string:
Info: Only 2/2 tests have run, let's try again later.
Convert it to a number during the parsing to fix that:
OK: All 2 tests passed so the pull-request can be merged.
Also fix the error mode: If the string is not in the expected format,
both split() and int() will raise a `ValueError`, not an
`AttributeError`.

fedora-bot: Fix --component parsing

---

fedora_bot.py

`status` is a tri-state (at least). We need to treat "pending" as "retry
later", not as success. Make the success condition explicit to avoid
unknown statuses from being misinterpreted.
Also add a check for "pending" to give a sensible message.
---
Noticed on https://src.fedoraproject.org/rpms/cockpit/pull-request/52 while my test was still pending. The JSON  looked like this:
```json
{
"flags": [
{
"comment": "Package tests for 5614c7b7: passed", 
"commit_hash": "5614c7b71863b28c95dd2f77787f148f1b633822", 
"date_created": "1653321767", 
"date_updated": "1653322255", 
"percent": null, 
"status": "success", 
"url": "https://koji.fedoraproject.org/koji/taskinfo?taskID=87410414", 
"user": {
"full_url": "https://src.fedoraproject.org/user/pingou", 
"fullname": "Pierre-YvesChibon", 
"name": …
```

fedora_bot: Don't treat pending tests as success

---

.github/workflows/poll-releases.yml

Osbuild has two tests in fedora dist-git actually: Scratch build and
a small smoke test. Let's fix that.

workflows: fix the number of osbuild tests

---

action.yml
fedora_bot.py

Cherry-pick updates from main and make all inputs optional.
This means that projects that only want to run Bodhi updates can do so by only supplying the `fedora_username` and `fedora_password` inputs.
If you only want to run the part of the action that merges green PRs you can do so by supplying the `fedora_apikey` and `num_tests` inputs.

Make inputs optional

---

Dockerfile

https://src.fedoraproject.org/rpms/fedpkg/c/06ae89e8e6ecac85a476cb92cceba4bd187c7b57?branch=f36
removed fedora-packager from the list of dependencies of fedpkg. This resulted
in bodhi-client not being pulled. We need it though, so we have to now install
it explicitly.

Dockerfile: Install bodhi-client

---

.github/workflows/reminder-bot.yml

Let's disable the weekly release reminders, as we really don't need them much anymore and they just create additional noise.
I've decided to only remove the trigger so far and keep the reminder stuff in the code so we can easily re-enable it should we find we need to.

reminder-bot: Disable weekly release reminders

---

reminder_bot.py

Currently only one developer receives the pings, but this is easily extensible.

reminder-bot: Ping frontend devs about open PRs

---

fedora_bot.py

Fix the pyflakes test rightfully complaining about an f-string missing placeholders.

Fix pyflakes test

---

.github/workflows/poll-releases.yml
README.md

Currently, we do excessive polling of pagure: every 30mins every day.
Since our releases are scheduled to always run on Wednesdays, let's rely on that fact and define an ample enough window for PRs to get caught. This means that when releasing on any other day (e.g. manually), one needs to trigger the bot, merge the pagure PRs manually or wait until the next Wednesday.
Note that while this removes quite some wasteful cycles, there's a risk for PRs in pagure getting stuck "until the next Wednesday".

Limit cron schedule

---

.github/workflows/reminder-bot.yml

Monthly reminder job is deprecated and is failing once a month. There is no reason to keep it anymore.

reminder-bot: Remove monthly reminder

---

fedora_bot.py

It seems that the response, when merging a MR in Fedora Pagure, may not include the 'message' property. In such case, the bot will fail with a traceback due to KeyError and won't log the received message.
Make the code more robust when accessing the response and print the whole response in case it was not in an expected format.

fedora_bot: make PR merge response parsing more robust

---

fedora_bot.py

Previously, the bot would log quite unhelpful messages in case any exception has been caught, such as:
```
Exception: error=KeyError('message'), type(error)=<class 'KeyError'>
```
This is less useful than printing the whole exception traceback, so let's do that instead if an exception is raised.

fedora_bot: print full exception traceback

---

fedora_bot.py

- fedora-bot: handle 'error' status in PR test results 
- fedora-bot: handle RuntimeError when processing component PRs

fedora-bot: improve error handling when processing component PRs
